language: rust
arch:
  - amd64
  - arm64
rust:
  - stable
  - beta
  - nightly
  - 1.33.0 # minimum supported version
  - 1.34.0 # minimum supported version
  - 1.35.0 # minimum supported version
  - 1.36.0 # minimum supported version
  - 1.37.0 # minimum supported version
  - 1.38.0 # minimum supported version
env:
  - CC=gcc
  - CC=clang
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
script:
  - cargo build -v && cargo test -v
  - (! rustc --version | grep -q nightly) || cargo bench -v
after_success:
  - ([[ "$(uname -m)" == "x86_64" ]] && [[ $CC == "gcc" ]] && rustc --version | grep -q nightly) && (cargo install -v --force cargo-travis; cargo coveralls -v --exclude-pattern=sss/)
